OPERATOR = "user_03"
BUG_REPORT = true
DB_NAME = "usonicapp"
DB_USER = "postgres"
DB_PASSWORD = "admin"
DB_HOST = "localhost"
DB_PORT = 5432
START_FREQUENCY = 42400
RANGE = 800
STEP = 1.0
PREVIOUS_FACTORY_NUMBER = "005.2023-0002"
PREVIOUS_COMPOSITION = "ПКИ"
PREVIOUS_DEVICE_MODEL = "model_01"
DISPLAY_RECORDS = 100
MODEL = "Волна-П"
COM_PORT = "COM3"
FPS = 15
REAL_TIME_CHART = true
