OPERATOR = "Абраменко Д.С."
BUG_REPORT = true
DB_NAME = "usonicapp"
DB_USER = "postgres"
DB_PASSWORD = "admin"
DB_HOST = "lapa14"
DB_PORT = 5432
START_FREQUENCY = 40774
RANGE = 188
STEP = 2.0
PREVIOUS_FACTORY_NUMBER = "007.2023-0002"
PREVIOUS_COMPOSITION = "ПК"
PREVIOUS_SERIES = "Волна"
PREVIOUS_DEVICE_MODEL = "УЗТА-0,4/22-ОМ (2)"
DISPLAY_RECORDS = 50
MODEL = "Волна-П"
COM_PORT = "COM3"
FPS = 15
REAL_TIME_CHART = false
VOLTAGE = 100
TERMINAL = true
EXPRESS_RANGE = "30000-45000"
EXPRESS_STEP = 50
