OPERATOR = "user_1"
BUG_REPORT = true
DB_NAME = "usonicapp"
DB_USER = "postgres"
DB_PASSWORD = "admin"
DB_HOST = "localhost"
DB_PORT = 5432
START_FREQUENCY = 20000
RANGE = 3000
STEP = 1.0
PREVIOUS_FACTORY_NUMBER = "002.2023.0002"
PREVIOUS_DEVICE_MODEL = "Сапфир"
DISPLAY_RECORDS = 100
MODEL = "Волна-П"
COM_PORT = "COM5"
