name: Build for Windows 7

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-win7:
    strategy:
      matrix:
        arch: ['x64', 'x86']
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python 3.8.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.8.10'
        architecture: ${{ matrix.arch }}

    - name: Install Windows 7 compatible packages
      working-directory: ./usonicapp
      run: |
        pip install --upgrade pip
        pip install "numpy==1.21.6"
        pip install "matplotlib==3.5.3"
        pip install "PyQt5==5.15.4"
        pip install "scipy==1.7.3"
        pip install "pandas==1.3.5"
        pip install "pyinstaller==5.6.2"
        pip install -r requirements.txt

    - name: Build with Windows 7 support
      working-directory: ./usonicapp
      run: pyinstaller usonicapp.spec --hidden-import numpy.core._multiarray_umath --hidden-import numpy.core._multiarray_tests

    - name: Add vcruntime140.dll manually if needed
      working-directory: ./usonicapp
      run: |
        # Копируем vcruntime140.dll из системы
        copy "C:\Windows\System32\vcruntime140.dll" dist\ 2>nul || echo "vcruntime140.dll not found, continuing without it"

    - name: Test basic functionality
      working-directory: ./usonicapp/dist
      run: |
        echo "Checking build files..."
        dir
        if exist usonicapp.exe (
            echo "EXE file created successfully"
        ) else (
            echo "EXE file not found"
            exit 1
        )

    - name: Upload Windows 7 compatible build
      uses: actions/upload-artifact@v4
      with:
        name: usonicapp-${{ matrix.arch }}-win7
        path: usonicapp/dist/
        retention-days: 30