name: Build Windows EXE

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  build-windows:
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
        architecture: ['x64', 'x86']
    runs-on: windows-latest  # Бесплатная Windows VM от GitHub

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }} (${{ matrix.architecture }})
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r usonicapp/requirements.txt
        pip install pyinstaller

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller usonicapp/usonicapp.spec


    - name: List built files
      run: dir dist\ /s

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: usonicapp-${{ matrix.python-version }}-${{ matrix.architecture }}
        path: dist/